### ISSUE TITLE
Bezier3 crashes Python with >30 waypoints

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/ndcurves#11]
I installed this package using `robotpkg-py27-curves` (I assume this is this repository?). I am trying to fit a 3-dimensional curve with a Bezier3 in Python. It works fine with 30 data points, but with 38 it crashes. I may have missed a crucial step or misunderstood the API. Here is what I do:

```python
curve_bezier = curves.bezier3(waypoints)
```

This is the stacktrace:

```bash
Thread 1 "python" received signal SIGFPE, Arithmetic exception.
0x00007fffe01e0249 in std::vector<curve::Bern<double>, std::allocator<curve::Bern<double> > > curve::makeBernstein<double>(unsigned int) ()
   from /opt/openrobots/lib/python2.7/site-packages/curves.so
(gdb) bt
#0  0x00007fffe01e0249 in std::vector<curve::Bern<double>, std::allocator<curve::Bern<double> > > curve::makeBernstein<double>(unsigned int) ()
   from /opt/openrobots/lib/python2.7/site-packages/curves.so
#1  0x00007fffe01e0504 in curve::bezier_curve<double, double, 3ul, true, Eigen::Matrix<double, 3, 1, 0, 3, 1> >* curve::wrapBezierConstructorTemplate<curve::bezier_curve<double, double, 3ul, true, Eigen::Matrix<double, 3, 1, 0, 3, 1> >, Eigen::Matrix<double, 3, -1, 0, 3, -1>, std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::aligned_allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > > >(Eigen::Matrix<double, 3, -1, 0, 3, -1> const&, double) () from /opt/openrobots/lib/python2.7/site-packages/curves.so
#2  0x00007fffe01d5076 in boost::python::objects::signature_py_function_impl<boost::python::detail::caller<curve::bezier_curve<double, double, 3ul, true, Eigen::Matrix<double, 3, 1, 0, 3, 1> >* (*)(Eigen::Matrix<double, 3, -1, 0, 3, -1> const&), boost::python::detail::constructor_policy<boost::python::default_call_policies>, boost::mpl::vector2<curve::bezier_curve<double, double, 3ul, true, Eigen::Matrix<double, 3, 1, 0, 3, 1> >*, Eigen::Matrix<double, 3, -1, 0, 3, -1> const&> >, boost::mpl::v_item<void, boost::mpl::v_item<boost::python::api::object, boost::mpl::v_mask<boost::mpl::vector2<curve::bezier_curve<double, double, 3ul, true, Eigen::Matrix<double, 3, 1, 0, 3, 1> >*, Eigen::Matrix<double, 3, -1, 0, 3, -1> const&>, 1>, 1>, 1> >::operator()(_object*, _object*) () from /opt/openrobots/lib/python2.7/site-packages/curves.so
#3  0x00007fffdfc99e55 in boost::python::objects::function::call(_object*, _object*) const () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1
---Type <return> to continue, or q <return> to quit---
#4  0x00007fffdfc9a008 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1
#5  0x00007fffdfca0bcb in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const ()
   from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1
#6  0x00007fffdff27493 in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<eigenpy::Exception, void (*)(eigenpy::Exception const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(eigenpy::Exception const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) () from /opt/openrobots/lib/libeigenpy.so
#7  0x00007fffdfca096f in boost::python::handle_exception_impl(boost::function0<void>) () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1
#8  0x00007fffdfc976c9 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1
#9  0x000055555567a3ae in ?? ()
#10 0x0000555555679f5a in ?? ()
```

**Comment by stonneau** [comment]
Hi @wxmerkt .

There are several points to this answer.

a) My guess is that this fails because the latest release of curves uses a naive implementation
of the Bernstein coefficients. More recent developments use a smarter implementation.
I just pushed the latest developments on devel if you want to try, it worked for me ?

b) Overall, it is probably a bad idea to use degree 38-1 polynomials. Even if the library is able 
to handle the load, I don't know what this leads to numerically. You should try to plot your Bezier curve to make sure it looks like what you expect. Otherwise, if infinite continuity is not your main issue, you can use a composition of Bezier curves instead. @JasonChmn could you provide some information on how to create such curves in c++ / python ?

Steve

**Comment by stonneau** [comment]
Also,
by default now the fastest way to evaluate a bezier curve is to use the horner scheme, traditionally used for evaluating polynomials. If you want more stability for large polynomials, the de casteljau algorithm is possibly more reliable.

The operator () uses the horner scheme, and the De Casteljau evaluation is not binded in python.
However if you have numerical issues I can do the binding for you, let me know if you need this feature
