### ISSUE TITLE
error when testing python scripts

### ISSUE THREAD

**Issue by robopassio** [loco-3d/ndcurves#62]
I am using ROS melodic.
There are several fails as below:
```
The following tests FAILED:
	  1 - python-curves (Failed)
	  5 - python-optimization (Failed)
	  6 - python-notebook (Failed)
	  7 - python-registration (Failed)
```
I tried to run `python test.py`
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    import eigenpy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/eigenpy/__init__.py", line 17, in <module>
    from .eigenpy import *
ImportError: libeigenpy.so: cannot open shared object file: No such file or directory
```

I think the problem is the CMAKE didn't link to the eigenpy of the suggested [ link](https://github.com/stack-of-tasks/eigenpy). Instead, it linked to ROS's eigenpy which is installed along with `pinocchio`.

The results of `cmake -DBUILD_PYTHON_INTERFACE=ON ..` is as follows:
```
-- Package version (ROS package.xml): 1.0.0
-- CMake versions older than 3.12 may warn when looking to Boost components. Custom macros are used to find it.
-- currently used  C++ standard: 201402
-- pinocchio searched on  FOUND. pinocchio at /opt/ros/melodic/lib/libpinocchio.so
-- boost_filesystem searched on  FOUND. boost_filesystem at /usr/lib/x86_64-linux-gnu/libboost_filesystem.so
-- boost_serialization searched on  FOUND. boost_serialization at /usr/lib/x86_64-linux-gnu/libboost_serialization.so
-- boost_system searched on  FOUND. boost_system at /usr/lib/x86_64-linux-gnu/libboost_system.so
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   serialization
--   system
-- eigenpy searched on  FOUND. eigenpy at /opt/ros/melodic/lib/libeigenpy.so
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   serialization
-- PythonInterp: /usr/bin/python
-- PYTHON_INCLUDE_DIRS:/usr/include/python2.7
-- PYTHON_INCLUDE_DIR:/usr/include/python2.7
-- PythonLibraries: /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- PythonLibraryDirs: /usr/lib/x86_64-linux-gnu
-- PythonLibVersionString: 2.7.17
-- Python site lib: lib/python2.7/dist-packages
CMake Warning at cmake/boost/FindBoost.cmake:1723 (message):
  No header defined for python-py27; skipping header check
Call Stack (most recent call first):
  cmake/boost.cmake:27 (FIND_PACKAGE)
  cmake/boost.cmake:93 (SEARCH_FOR_BOOST_COMPONENT)
  CMakeLists.txt:47 (SEARCH_FOR_BOOST_PYTHON)


CMake Warning at cmake/boost.cmake:102 (MESSAGE):
  Impossible to check Boost.Python version.  Trying with 'python'.
Call Stack (most recent call first):
  CMakeLists.txt:47 (SEARCH_FOR_BOOST_PYTHON)


-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python
-- Boost_PYTHON_LIBRARY: /usr/local/lib/libboost_python.so
-- Doxygen rendering: using LaTeX backend
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/cubic_spline/ndcurves/build
```
Here
```
-- eigenpy searched on  FOUND. eigenpy at /opt/ros/melodic/lib/libeigenpy.so
-- Boost version: 1.58.0
```
I think it should be `/opt/openrobots/lib/python2.7/site-packages`?

**Comment by wxmerkt** [comment]
It's recommended not to mix eigenpy from the ROS PPA with the robotpkg PPA. It is possible to use both at the same time, but you need to be careful in the order of exporting the path variables (LD_LIBRARY_PATH etc.) and/or sourcing ROS. E.g. if you first source ROS and then export the path variables for robotpkg it works as you intended by prepending. Either way it's better not to mix them.

**Comment by stonneau** [comment]
@robopassio did @wxmerkt comment help you solve your issue ?
